spring.application.name=ordini-e-pagamenti-auth

server.servlet.context-path=/${CONTEXT_PATH:api}

# Datasource (DB)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
