spring.application.name=ordini-e-pagamenti-auth

server.servlet.context-path=/${CONTEXT_PATH:api}

# Datasource (DB)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Securiy & Jwt
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration=${JWT_EXPIRATION_MILLIS:120000}
